Kristina moen/add subjects
cjrocheleau/MATH633_MedicalImaging pull request #31
Opened 2023-04-27 15:53 UTC by kristinamoen

Add folder for Mason/Joel/Kristina's project

2023-04-27 17:43 UTC, KylerHoward requested changes
Kristina, can you remove the two .DS_Store files that it shows as being issues and send another push up? Let me know if that doesn't make sense.

2023-04-29 14:31 UTC, cjrocheleau approved these changes
Looks good now, hopefully it allows the merge now,

2023-04-29 14:31 UTC, cjrocheleau commented on .gitignore
That's the stuff! Good idea.

2023-04-29 14:47 UTC, KylerHoward approved these changes

2023-04-29 14:47 UTC, merged